"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { getUpcyclingIdeasAction } from "@/app/actions";
import { Loader2, Sparkles, Lightbulb } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";

type IdeaButtonProps = {
  materialName: string;
  customizationRequest?: string;
};

export default function IdeaButton({ materialName, customizationRequest }: IdeaButtonProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [ideas, setIdeas] = useState<string[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleFetchIdeas = async () => {
    if (ideas.length > 0) return; // Don't re-fetch if ideas are already there

    setIsLoading(true);
    setError(null);
    const result = await getUpcyclingIdeasAction(materialName, customizationRequest);
    if (result.error) {
      setError(result.error);
    } else {
      setIdeas(result.ideas);
    }
    setIsLoading(false);
  };

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>
        <Button onClick={handleFetchIdeas} className="w-full bg-accent text-accent-foreground hover:bg-accent/90">
          <Sparkles className="mr-2 h-4 w-4" />
          Get AI Ideas
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle className="font-headline text-2xl">Upcycling Ideas for {materialName}</DialogTitle>
          <DialogDescription>
            {customizationRequest 
              ? `AI-generated ideas based on your request: "${customizationRequest}"`
              : "Here are a few creative ideas generated by AI to inspire your next project."
            }
          </DialogDescription>
        </DialogHeader>
        <div className="py-4">
          {isLoading && (
            <div className="flex items-center justify-center h-24">
              <Loader2 className="h-8 w-8 animate-spin text-primary" />
              <p className="ml-4">Generating ideas...</p>
            </div>
          )}
          {error && (
            <Alert variant="destructive">
              <AlertTitle>Error</AlertTitle>
              <AlertDescription>{error}</AlertDescription>
            </Alert>
          )}
          {!isLoading && ideas.length > 0 && (
            <ul className="space-y-3">
              {ideas.map((idea, index) => (
                <li key={index} className="flex items-start">
                  <Lightbulb className="h-5 w-5 text-yellow-500 mr-3 mt-1 flex-shrink-0" />
                  <span>{idea}</span>
                </li>
              ))}
            </ul>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
